(defmacro ++1 (&rest args)
(cons 'progn (mapcar (lambda (x) (list 'incf x)) args)))
(setq x 1)
(setq z 3)
(setq h 6)
(print (macroexpand '(++1 x z h)))
(++1 x z h)
(print (list x z h))

(defmacro x*x (&rest args)
(cons 'progn (mapcar (lambda (x) (list 'setq x (list '* x x))) args)))
(setq x 1)
(setq z 3)
(setq h 6)
(print (macroexpand '(x*x x z h)))
(x*x x z h)
(print (list x z h))
